### ISSUE TITLE
Creating issues from Git

### ISSUE THREAD

**Issue by fgm** [developmentseed/FeatureServer#10]
Hi. I have been using FServer with manually generated releases, but I cannot find how to have them be automatically built from git tags, although code to do this seems to be present in the sources, like FserverProject_git::create_package().

drush fserver-package looks like it should build releases, but it constantly says "up to date", and nothing happens. Any pointers ?

**Comment by joestewart** [comment]
Does drush fserver-status projectname show any releases?

I found that tags had to be in the drupal-6--1-0-alpha1 format.

**Comment by fgm** [comment]
Thanks, I found as much in the meantime. For anyone interested, tags must match this regex: 

```
/^(?P<project>\w+)-(?P<core>\d+)--(?P<major>\d+)-(?P<patch>\d+)-?(?P<extra>\w+)?$/
```

This is in `fserver_parse_tag_name()` and the package generation functions like `FserverProject_git::create_package()` use that function to filter only tags matching this regex.
