### ISSUE TITLE
Missing view for update_feed_api

### ISSUE THREAD

**Issue by dominikb1888** [developmentseed/FeatureServer#14]
Maybe I've completely overlooked something, but feature server projects can't be pulled via the initial feed update, when using update_feed_api. When implementing the update_feed class this module looks for "http://example.com/fserver/project-list/all" to update its database tables with the complete release history of each feature on a server. The view shipped with fserver is only listening to the module_name and build arguments, so submitting "project-list/all" doesn't return the need complete xml list of projects. 

I've created a view listing the complete XML of the feature server at "fserver/project-list/all". this seemed to be the logical way for me. Please correct me if I am wrong.

Here's the export of my view:

<pre>
$view = new view;
$view->name = 'fserver_updates_project_list';
$view->description = 'Feature Server > Update feed all Projects list';
$view->tag = 'fserver';
$view->view_php = '';
$view->base_table = 'node';
$view->is_cacheable = FALSE;
$view->api_version = 2;
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
$handler = $view->new_display('default', 'Defaults', 'default');
$handler->override_option('relationships', array(
  'field_fserver_project_nid' => array(
    'label' => 'Project',
    'required' => 1,
    'delta' => -1,
    'id' => 'field_fserver_project_nid',
    'table' => 'node_data_field_fserver_project',
    'field' => 'field_fserver_project_nid',
    'relationship' => 'none',
  ),
  'field_fserver_file_fid' => array(
    'label' => 'Package',
    'required' => 1,
    'delta' => -1,
    'id' => 'field_fserver_file_fid',
    'table' => 'node_data_field_fserver_file',
    'field' => 'field_fserver_file_fid',
    'relationship' => 'none',
  ),
));
$handler->override_option('fields', array(
  'field_fserver_api_value' => array(
    'label' => 'API version',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'custom',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_api_value',
    'table' => 'node_data_field_fserver_api',
    'field' => 'field_fserver_api_value',
    'relationship' => 'none',
  ),
  'field_fserver_versionextra_value' => array(
    'label' => 'Extra version',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_versionextra_value',
    'table' => 'node_data_field_fserver_versionextra',
    'field' => 'field_fserver_versionextra_value',
    'relationship' => 'none',
  ),
  'field_fserver_versionmajor_value' => array(
    'label' => 'Major version',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_versionmajor_value',
    'table' => 'node_data_field_fserver_versionmajor',
    'field' => 'field_fserver_versionmajor_value',
    'relationship' => 'none',
  ),
  'field_fserver_versionpatch_value' => array(
    'label' => 'Patch version',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_versionpatch_value',
    'table' => 'node_data_field_fserver_versionpatch',
    'field' => 'field_fserver_versionpatch_value',
    'relationship' => 'none',
  ),
  'created' => array(
    'label' => 'Post date',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'date_format' => 'custom',
    'custom_date_format' => 'U',
    'exclude' => 0,
    'id' => 'created',
    'table' => 'node',
    'field' => 'created',
    'relationship' => 'none',
  ),
  'title' => array(
    'label' => 'Project title',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'exclude' => 0,
    'id' => 'title',
    'table' => 'node',
    'field' => 'title',
    'relationship' => 'field_fserver_project_nid',
  ),
  'field_fserver_name_value' => array(
    'label' => 'Project name',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_name_value',
    'table' => 'node_data_field_fserver_name',
    'field' => 'field_fserver_name_value',
    'relationship' => 'field_fserver_project_nid',
  ),
  'nid' => array(
    'label' => 'Project URL',
    'alter' => array(
      'alter_text' => 1,
      'text' => 'node/[nid]',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'exclude' => 0,
    'id' => 'nid',
    'table' => 'node',
    'field' => 'nid',
    'relationship' => 'field_fserver_project_nid',
  ),
  'filepath' => array(
    'label' => 'File path',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_file' => 0,
    'exclude' => 0,
    'id' => 'filepath',
    'table' => 'files',
    'field' => 'filepath',
    'relationship' => 'field_fserver_file_fid',
  ),
  'filesize' => array(
    'label' => 'Filesize',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'file_size_display' => 'bytes',
    'exclude' => 0,
    'id' => 'filesize',
    'table' => 'files',
    'field' => 'filesize',
    'relationship' => 'field_fserver_file_fid',
  ),
  'nid_1' => array(
    'label' => 'Release URL',
    'alter' => array(
      'alter_text' => 1,
      'text' => 'node/[nid_1]',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'exclude' => 0,
    'id' => 'nid_1',
    'table' => 'node',
    'field' => 'nid',
    'relationship' => 'none',
  ),
  'mdhash' => array(
    'label' => 'MD5 hash',
    'alter' => array(
      'alter_text' => FALSE,
      'text' => '',
      'make_link' => FALSE,
      'path' => '',
      'alt' => '',
      'link_class' => '',
      'prefix' => '',
      'suffix' => '',
      'trim' => FALSE,
      'max_length' => '',
      'word_boundary' => TRUE,
      'ellipsis' => TRUE,
      'strip_tags' => FALSE,
      'html' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'mdhash',
    'table' => 'files',
    'field' => 'mdhash',
    'relationship' => 'field_fserver_file_fid',
  ),
  'field_fserver_security_value' => array(
    'label' => 'Security release',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_security_value',
    'table' => 'node_data_field_fserver_security',
    'field' => 'field_fserver_security_value',
    'relationship' => 'none',
  ),
  'field_fserver_recommended_value' => array(
    'label' => 'Recommended',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_recommended_value',
    'table' => 'node_data_field_fserver_recommended',
    'field' => 'field_fserver_recommended_value',
    'relationship' => 'none',
  ),
  'field_fserver_type_value' => array(
    'label' => 'Type',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'plain',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_type_value',
    'table' => 'node_data_field_fserver_type',
    'field' => 'field_fserver_type_value',
    'relationship' => 'field_fserver_project_nid',
  ),
  'field_fserver_redirect_value' => array(
    'label' => 'Type',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'strip_tags' => 0,
      'html' => 0,
    ),
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'plain',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_fserver_redirect_value',
    'table' => 'node_data_field_fserver_redirect',
    'field' => 'field_fserver_redirect_value',
    'relationship' => 'field_fserver_project_nid',
  ),
));
$handler->override_option('sorts', array(
  'release_tag' => array(
    'order' => 'DESC',
    'id' => 'release_tag',
    'table' => 'views',
    'field' => 'release_tag',
    'relationship' => 'none',
  ),
  'status' => array(
    'order' => 'DESC',
    'id' => 'status',
    'table' => 'node',
    'field' => 'status',
    'override' => array(
      'button' => 'Override',
    ),
    'relationship' => 'none',
  ),
));
$handler->override_option('filters', array(
  'status' => array(
    'operator' => '=',
    'value' => '1',
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'status',
    'table' => 'node',
    'field' => 'status',
    'relationship' => 'none',
  ),
  'type' => array(
    'operator' => 'in',
    'value' => array(
      'fserver_release' => 'fserver_release',
    ),
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'type',
    'table' => 'node',
    'field' => 'type',
    'relationship' => 'none',
  ),
));
$handler->override_option('access', array(
  'type' => 'none',
));
$handler->override_option('cache', array(
  'type' => 'none',
));
$handler->override_option('items_per_page', 0);
$handler->override_option('style_options', array(
  'grouping' => '',
));
$handler = $view->new_display('feed', 'Update XML feed', 'feed_1');
$handler->override_option('style_plugin', 'updatexml');
$handler->override_option('style_options', array(
  'mission_description' => FALSE,
  'description' => '',
  'project' => array(
    'title' => 'title',
    'short_name' => 'field_fserver_name_value',
    'api_version' => 'field_fserver_api_value',
    'link' => 'nid',
    'type' => 'field_fserver_type_value',
    'redirect' => 'field_fserver_redirect_value',
  ),
  'release' => array(
    'version_major' => 'field_fserver_versionmajor_value',
    'version_patch' => 'field_fserver_versionpatch_value',
    'version_extra' => 'field_fserver_versionextra_value',
    'release_link' => 'nid_1',
    'download_link' => 'filepath',
    'date' => 'created',
    'mdhash' => 'mdhash',
    'filesize' => 'filesize',
    'security' => 'field_fserver_security_value',
    'recommended' => 'field_fserver_recommended_value',
  ),
));
$handler->override_option('row_plugin', '');
$handler->override_option('path', 'fserver/project-list/all');
$handler->override_option('menu', array(
  'type' => 'none',
  'title' => '',
  'description' => '',
  'weight' => 0,
  'name' => 'navigation',
));
$handler->override_option('tab_options', array(
  'type' => 'none',
  'title' => '',
  'description' => '',
  'weight' => 0,
  'name' => 'navigation',
));
$handler->override_option('displays', array());
$handler->override_option('sitename_title', FALSE);
</pre>

**Comment by EugenMayer** [comment]
as the author of update_feed_api  iam using this feed for just forever. Since 2 days, i dont have a projects-list/alkl anymore. Iam still inverstigating, but thats pretty odd.

**Comment by EugenMayer** [comment]
well, fixed. Somehow nodereference_url wasnt available anymore, which deactivated fserver_bonus. fserver_bonus is the one providing the full-project list feed - so thats all you need. Iam sure we will add this to the core-fserver in the near future, just check http://drupal.org/project/fserver

**Comment by dominikb1888** [comment]
Thanks for the reply! I will update to the latest dev and check if the issue is resolved on my site as well.
