### ISSUE TITLE
Integration with Node Reference URL

### ISSUE THREAD

**Issue by JoshOldenburg** [developmentseed/FeatureServer#5]
I modified the fserver.module file to add the url to the 'add new release' link. The code is: (this is the first function in fserver.module)
function fserver_link($type, $object, $teaser = FALSE) {
  // Only allow releases to be added if packaging method is 0 => 'Manual'.
  $links = array();
  if ($type == 'node' && $object->type == 'fserver_project' && empty($object->field_fserver_method[0]['value'])) {
    $item = menu_get_item('node/add/fserver-release');
    if ($item && $item['access']) {
      $links['fserver-add-release'] = array(
        'title' => t('Add new @release', array('@release' => strtolower($item['title']))),
        'href' => 'node/add/fserver-release/' . $object->nid,
      );
    }
  }
  return $links;
}

Notice /' . $object->nid,
The object->nid is what I added.

**Comment by kostajh** [comment]
Looks good to me. Works as expected.

**Comment by JoshOldenburg** [comment]
Now in my pull request
